---
- hosts: tag_Web_Server_True
  tasks:
          - name: ensure apache2 is installed and latest
            apt: name=apache2 state=latest
          - name: start apache2
            service:
                    name: apache2
                    state: started
          - name: copy default config file and restart apache2
            copy:
                    src: /home/ubuntu/ansible/default_site.cfg
                    dest: /etc/apache2/sites-available/000-default.conf
          - name: copy apache2 config file and restart apache2
            copy:
                    src: /home/ubuntu/ansible/apache2.conf
                    dest: /etc/apache2/apache2.conf
          - name: enable mod_cgi
            file:
                    src: /etc/apache2/mods-available/cgi.load
                    dest: /etc/apache2/mods-enabled/cgi.load
                    state: link
          - name: enable mod_ssi
            file:
                    src: /etc/apache2/mods-available/include.load
                    dest: /etc/apache2/mods-enabled/include.load
                    state: link
          - name: create symlink for default site
            file:
                    src: /etc/apache2/sites-available/000-default.conf
                    dest: /etc/apache2/sites-enabled/000-default.conf
                    state: link
          - name: restart apache2
            service:
                    name: apache2
                    state: restarted
