---
- hosts: tag_Web_Server_True
  tasks:
          - name: ensure nginx is installed and latest
            apt: name=nginx state=latest
          - name: start nginx
            service:
                    name: nginx
                    state: started
          - name: copy nginx config file and restart nginx
            copy:
                    src: /home/ubuntu/ansible/nginx_static_site.cfg
                    dest: /etc/nginx/sites-available/static_site.cfg
          - name: create symlink
            file:
                    src: /etc/nginx/sites-available/static_site.cfg
                    dest: /etc/nginx/sites-enabled/default
                    state: link
          - name: restart nginx
            service:
                    name: nginx
                    state: restarted
